#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker600)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "2014 Autonomous Functions.h"
task main()
{
	while(true)
	{
		nxtDisplayString(1,"ultrasonic: %d", SensorValue(ultrasonic));
		wait1Msec(10);
	}
}
