#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S3,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     backRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     camMotor,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     collectionMotor, tmotorTetrix, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "2014 Autonomous Functions.h"

//distance from top of ramp to bottom: 58 inches
//distance from ramp to rolling goals: approximately 48 inches
//distance from ramp to centerpiece: 31 inches
//distance from end of ramp to wall: 23 3/4 inches

task main()
{
	//waitForStart();
	initializeRobot();
	nmotorEncoder[pinMotor] = 0;
	startTask(printHeading);

	//drive off the ramp backwards towards the 60cm rolling goal
		drive(-58, 20, 20)//drive backwards 58 power 20
		drive(-54, 50, 50)//drive backwards 54 inches power 50

	//capture 60cm rolling gwait10Msec
		motor[pinMotor] = 40;//move goal grabbing device to capture the goal
		while(nMotorEncoder[pinMotor] < 60)
		{
		}
		motor[pinMotor] = 0;
		bFloatDuringInactiveMotorPWM = false;


	//put the balls into the rolling goal
		drive(1, 20, 20);//drive forward to secure the goal
		/*motor[liftingMotor] = 30;//drive the motor to raise the arm
		wait1Msec(500);
		motor[liftingMotor] = 0;
		wait1Msec(100);
		motor[ballReleaseMotor] = 30;//spin the motor to release the balls
		wait1Msec(200);
		motor[ballReleaseMotor] = 0;*/

	//drive to the scoring area
		turn(-90, 50);//turn 90 degrees left
		drive(-35, 50, 50);//drive backwards 35 inches
		turn(-90, 50);//turn 90 degrees left
		drive(-98, 50, 50);//drive backwards 98 inches
		turn(90, 50);//turn 90 degrees right
		drive(-10, 50, 50);//drive backwards 10 inches

	//detatch the cammotor
	/*	motor[camMotor] = -10;//drive the cammotor backwards
		wait1Msec(200);
		motor[camMotor] = 0;*/

}
