#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     winchMotor,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     hookMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     backRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collectionMotor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    leftGate,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rightGate,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    bucket,               tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "2014 Autonomous Functions.h"
//#include "JoystickDriver.c"

// distance from top of ramp to bottom: 58 inches
// distance from ramp to rolling goals: ~48 inches
// distance from ramp to centerpiece: 31 inches
// distance from end of ramp to wall: 23.75 inches

bool upBucket = true;
bool openGate = false;
int bucketUpPos = 150;
int bucketDownPos = 50;
int leftGateClosedPos = 45;
int leftGateOpenPos = 165;
int rightGateClosedPos = 165;
int rightGateOpenPos = 45;

task servoStay()
{
	while(true)
	{
		if(openGate)
		{
			servo[leftGate] = leftGateOpenPos;
			servo[rightGate]= rightGateOpenPos;
		}
		else
		{
			servo[leftGate] = leftGateClosedPos;
			servo[rightGate]= rightGateClosedPos;
		}
	}
}

task raise()
{
	nMotorEncoder(winchMotor) = 0;
	nMotorEncoderTarget(winchMotor) = 11000;
	motor(winchMotor) = 60;
	while(nMotorRunState[winchMotor] != runStateIdle)
	{
	}
	motor(winchMotor) = 0;
}

task main()
{

	 // waitForStart();
	 initializeRobot();
	 startTask(servoStay);

	 drive(-5000, -30, -30);
	 wait1Msec(1000);
	 startTask(raise);
	 openGate = true;
	 wait1Msec(5000);
	 drive(-4000, -35, -35)
	 servo[bucket] = 60;
	 wait1Msec(500);
   servo[bucket] = 50;
   wait1Msec(30000);


		// drive forward to secure the goal
		// drive(1, 20, 20);
		// wait1Msec(100);
}
