#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
// #pragma config(Motor,  mtr_S1_C3_1,     collectionMotor, tmotorTetrix, openLoop, reversed)
// #pragma config(Motor,  mtr_S1_C3_2,     camMotor,      tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "2014 Autonomous Functions.h"

task main()
{
	startTask(display);
	drive(4000, 50, 50, false);
//	while (true)
//	{
//		motor[backRight] = 10;
//		motor[backLeft] = 10;
//		motor[frontRight] = 10;
//		motor[frontLeft] = 10;
//	}// 83
	//turn(45, 80); // 45
	//drive(-40, 80, 80, false); // 26
	//turn(-45, 80); // 90
	//drive(0, 80, 80, true);// 26 false
}
