#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
// #pragma config(Motor,  mtr_S1_C3_1,     collectionMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     camMotor,      tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "2014 Autonomous Functions.h"

//distance from top of ramp to bottom: 58 inches
//distance from ramp to rolling goals: approximately 48 inches
//distance from ramp to centerpiece: 31 inches
//distance from end of ramp to wall: 23 3/4 inches

task main()
{
	//waitForStart();
	initializeRobot();
	startTask(printHeading);
	//drive(8000,50,50,false);
	turn(-45, 30);
	//motor[backLeft] = 50;
	//motor[backRight] = 50;
	//motor[frontLeft] = 50;
	//motor[frontRight] = 50;


	//motor[backLeft] = 50;
	//motor[frontLeft] = 50;
	//motor[frontRight] = -50;
	//motor[backRight] = -50;

	//wait1Msec(2000);

	//motor[backLeft] = 0;
	//motor[backRight] = 0;
	//motor[frontLeft] = 0;
	//motor[frontRight] = 0;

	//startTask(display);*/

	//drive off the ramp backwards towards the 60cm rolling goal
		drive(-58, 20, 20, false)//drive backwards 58 power 20
		drive(-54, 50, 50, false)//drive backwards 54 inches power 50

	//capture 60cm rolling goal
		motor[camMotor] = 10;//move goal grabbing device to capture the goal
		wait1Msec(200);
		motor[camMotor] = 0;


	//put the balls into the rolling goal
		drive(1, 20, 20, false);//drive forward to secure the goal
		//drive the motor to raise the arm
		//spin the motor to release the balls

	//drive to the scoring area
		turn(-90, 50);//turn 90 degrees left
		drive(-35, 50, 50, false);//drive backwards 35 inches
		turn(-90, 50);//turn 90 degrees left
		drive(-98, 50, 50, false);//drive backwards 98 inches
		turn(90, 50);//turn 90 degrees right
		drive(-10, 50, 50, false);//drive backwards 10 inches

	//?detatch?

}
