#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	for(int i = 0; i < 4; i++)
	{
		int degreesToTurn = -90;
		float degreesSoFar = 0;
		int initialTurnReading = SensorValue[gyro];

		nSyncedMotors = synchAB;
		nSyncedTurnRatio = -100;
		motor[motorA] = -15*sgn(degreesToTurn);

		while(abs(degreesSoFar) < abs(degreesToTurn))
		{
			wait1Msec(10);
			int currentGyroReading = SensorValue[gyro] - initialTurnReading;
			degreesSoFar = degreesSoFar + currentGyroReading*.01;
		}
		motor[motorA] = 0;
		wait1Msec(500);
	}

	for(int i = 0; i < 4; i++)
	{
		int degreesToTurn = 90;
		float degreesSoFar = 0;
		int initialTurnReading = SensorValue[gyro];

		nSyncedMotors = synchAB;
		nSyncedTurnRatio = -100;
		motor[motorA] = -15*sgn(degreesToTurn);

		while(abs(degreesSoFar) < abs(degreesToTurn))
		{
			wait1Msec(10);
			int currentGyroReading = SensorValue[gyro] - initialTurnReading;
			degreesSoFar = degreesSoFar + currentGyroReading*.01;
		}
		motor[motorA] = 0;
		wait1Msec(500);
	}
}
