#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     winchMotor,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     hookMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     backRight,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     frontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collectionMotor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    leftGate,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rightGate,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    bucket,               tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"

task main()
{
	// Create struct to hold sensor data
  tHTIRS2 irSeeker;
  // Initialise and configure struct and port
  initSensor(&irSeeker, S3);

	int leftSpeed = 40;
	int rightSpeed = 40;

	OpenWrite(
	while (true)
	{
		int leftSum = irSeeker.dcValues[0] + irSeeker.dcValues[1];
		int rightSum = irSeeker.dcValues[3] + irSeeker.dcValues[4];
		if (leftSum < rightSum && rightSum - leftSum > 22)
		{
			leftSpeed = 40;
			rightSpeed = -40;
		}
		else if (rightSum < leftSum && leftSum - rightSum > 22)
		{
			leftSpeed = -40;
			rightSpeed = 40;
		}
		else
		{
			leftSpeed = -40;
			rightSpeed = -40;
		}

		motor[frontRight] = rightSpeed;
		motor[backRight] = rightSpeed;
		motor[frontLeft] = leftSpeed;
		motor[backLeft] = leftSpeed;

		readSensor(&irSeeker);

		writeDebugStreamLine("irSeeker values");
		for (int i = 0; i < 5; i++)
		{
			writeDebugStreamLine("irSeeker[%d]: %d", i, irSeeker.dcValues[i]);
		}
		for (int i = 0; i < 5; i++)
		{
			writeDebugStreamLine("irSeeker[%d]: %d", i, irSeeker.dcValues[i]);
		}


		writeDebugStreamLine("-----------------------");
		wait1Msec(50);
	}
}
